#!/bin/sh

weather () {
        # Location Santana, SP - Brazil
        local str=`curl -Ss 'https://darksky.net/forecast/-23.4861,-46.628/si12/en'| \
            perl -lne 'print "$1 $2" if /(Feels Like:|Low:|High:)[^\d]*(\d{1,2})/'`

        local temp=`echo $str|
            perl -lne 'print $1 if /Feels Like: (\d{1,2})/'`

        local low=`echo $str|
            perl -lne 'print $1 if /Low: (\d{1,2})/'`

        local high=`echo $str|
            perl -lne 'print $1 if /High: (\d{1,2})/'`

        echo -e "\n"
        echo "☼ Temp "$temp"°C «Min: "$low""°C, Max: "$high""°C»"
        echo -e "\n"

}

